### PR TITLE
docs(readme): include installation notes for Chocolatey users

### PR DESCRIPTION
**Pull request by zlesnr**

### CODE REVIEW

**Comment by jthurman42** [comment]
Should we just wait to document until it is fully published?

**Comment by zlesnr** [comment]
We can hold this open for a bit.  I'll check back tomorrow and see where we're at in their ecosystem.

**Comment by zlesnr** [comment]
Still not published.

**Comment by zlesnr** [comment]
https://chocolatey.org/packages/newrelic-cli still not reviewed.

**Comment by jthurman42** [comment]
Blocked on #305

**Pull request merged**
