### PR TITLE
feat: add fish completion support and update doc

### PR DESCRIPTION
**Pull request by chenrui333**
add fish completion support and update doc ([reference](https://github.com/spf13/cobra/blob/master/shell_completions.md))

### CODE REVIEW

**Comment by chenrui333** [comment]
It would be good to include fish completion for brew users. Homebrew/homebrew-core#79943

**Comment by chenrui333** [comment]
cc @Julien4218

**Comment by ctrombley** [comment]
Hi @chenrui333, we'd like to merge this contribution.  Would you please do an interactive rebase and add a "chore: " prefix to your second commit?  Thanks!

**Comment by ctrombley** [comment]
Cherry picking into #980 and continuing work there.  Thanks @chenrui333 !

**Comment by chenrui333** [comment]
Thanks @ctrombley!

**Pull request closed without merging**
