### PR TITLE
doc: add homebrew release badge

### PR DESCRIPTION
**Pull request by chenrui333**
Adding a homebrew release badge to x-post the homebrew release info.

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @Julien4218

**Comment by ctrombley** [comment]
Hi @chenrui333, we'd like to merge this contribution. Would you please do an interactive rebase and update your commit's prefix from "doc:" to "docs:"? Thanks!

**Comment by ctrombley** [comment]
Cherry picking this commit in #979 and continuing work there.  Thanks @chenrui333 !

**Comment by chenrui333** [comment]
Thanks @ctrombley!

**Pull request closed without merging**
